[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
features = { version = "0.1.0", path = "../features" }
sdl2 = { version = "0.37.0", features = ["ttf"] }
vectors = { path = "../../vectors" }
